### ISSUE TITLE
[Serverless 4] Upgrade Request

### ISSUE THREAD

**Issue by danhnguyeen** [serverless-operations/serverless-step-functions#626] opened 2024-09-16 08:37 UTC
Hi there,
Are there any plans to upgrade this library to support Serverless Version 4?
I tried installing the library, but it threw bellow error

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: serverless-step-functions@3.21.0
npm error Found: serverless@4.3.2
npm error node_modules/serverless
npm error   peer serverless@"^4.0.0" from serverless-offline@14.3.1
npm error   node_modules/serverless-offline
npm error     dev serverless-offline@"^14.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer serverless@"^2.32.0 || 3" from serverless-step-functions@3.21.0
npm error node_modules/serverless-step-functions
npm error   dev serverless-step-functions@"^3.21.0" from the root project
npm error
npm error Conflicting peer dependency: serverless@3.39.0
npm error node_modules/serverless
npm error   peer serverless@"^2.32.0 || 3" from serverless-step-functions@3.21.0
npm error   node_modules/serverless-step-functions
npm error     dev serverless-step-functions@"^3.21.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

Currently, I’m able to bypass this by using `npm install --legacy-peer-deps`, and it works for now. 
However, it would be great to have official support for Serverless Version 4
Thanks a lot

**Comment by threes-was-taken** [comment] 2024-09-23 06:00
Hi @danhnguyeen 

I made sure v4 is supported by contributing the required change to this repository (PR #615). It's also, already, merged into the master branch **but** the maintainers have yet to deploy a new release containing this change. 

I started a discussion and made an issue (#625) asking to release the latest changes so v4 is supported.. Others, like yourself, and I are still waiting for a new release so we can fully upgrade to v4..

A thumbs up on the issue is appreciated so the maintainers, hopefully, give more attention to the release.

**Comment by ynishimura** [comment] 2024-09-30 02:30
Is the release of this PR still pending?

**Comment by threes-was-taken** [comment] 2024-09-30 05:54
> Is the release of this PR still pending?

@ynishimura 
We're looking into it. There seems to be a misconfiguration of semantic-release where commits regarding dependency updates and upgrades, by someone and/or dependabot, don't qualify as relevant changes for a release. See the discussion on issue #624.

**Closed** 2024-10-03 12:38 UTC
